### ISSUE TITLE
Debian Bullseye removes libcrystalhd-dev package

### ISSUE THREAD

**Issue by mjlocat** [MythTV/packaging#107]
Debian Bullseye has [removed the libcrystalhd-dev package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934242). This is a Build-Depend for this package. 

Given this is only a dependency for i386 and amd64 architectures, seems like it might be optional and based on what's discussed in the bug linked above, may have never actually worked in Debian. Not sure about Ubuntu or other Debian based distros. Going to try removing this Build-Depend and see what happens. If it works for me, I'll submit a PR for this.

**Comment by superm1** [comment]
Considering the hoops needed to go through are there even a lot of users for that stuff?

If it's getting removed in bullseye it's likely to get removed in Ubuntu too eventually.  I think we should just drop the build dependency and support in the packaging all together.  If people use it, they'll complain and it can be made optional as you say.

**Comment by mjlocat** [comment]
That's what I was thinking as well. I've got a branch with this change on my fork, just need to run it through my ubuntu VMs to verify that it'll still build the package successfully before I submit the PR. Might kick off that test tonight so I can submit the PR tomorrow. I honestly have no idea what this library does. Funny enough, the package exists on my main Debian Bullseye machine because it was an upgrade from Buster. Testing in a clean VM, I don't seem to be able to find it in backports or anything else. Might have been in deb-multimedia, but that repo isn't an official Debian repo.

**Comment by knowledgejunkie** [comment]
For reference more than anything: CrystalHD support in Debian and Ubuntu is as follows:

- Debian: https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=crystalhd

- Ubuntu: https://packages.ubuntu.com/search?keywords=crystalhd&searchon=names&section=all

As can be seen, Crystal HD support is no longer in Debian since Debian 10 "Buster" (due to missing firmware), but continues to live on in the current Ubuntu 21.10 release and is listed for the proposed 22.04 LTS release.

I agree with @superm1 that we should drop support now

**Comment by mjlocat** [comment]
Now that the PR has been merged, I'll go ahead and close this issue.

**Comment by superm1** [comment]
If you think this makes sense on fixes branches please feel free to submit cherry picks backwards too.
