### ISSUE TITLE
android 

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/packaging#126]
Not sure how to do the whole pull request and make the patches myself, so I'll just detail the few changes I see that I feel need to be made.

In the first paragraph the link to the Docker solution is bad it should be https://github.com/MythTV/packaging/tree/master/android/docker

I suggest that before the 2 git clone statements that the user should go to their github.com account and create ssh keys per the documentation at https://docs.github.com/en/authentication/connecting-to-github-with-ssh

After the 2 git clone statements it needs to be mentioned that the user needs to cd into each of the mythtv and packaging directories under workdir and git checkout fixes/32 or whatever version they want.

At the end of Step 1. I think you need to add the 2 statements that will be required in the building process later:

git config --global user.name "John Doe"
git config --global user.email johndoe@example.com

I got stuck a lot in Step 2. In bullet 1, I think it needs to be:
       In Android Studio, choose More Action / SDK Manager
in the next 2 bullets of Step 2, I think it needs to be very specific as to the steps. I found that Android is not very forgiving when building mythfrontend.  I had to select Android 8 (Oreo) API 26, Build-tools 29.03, NDK 21.2.7075529, CMake.

On the part about about release keys more information would be useful. I didn't do anything about keys and I did get an error about no key provided [ignored]. I had to run the statement again but eventually I got the apk file uploaded to the FireTV.

Step 3 is missing 2 dependencies:
libtool
autopoint

**Comment by bennettpeter** [comment]
Thank you for the updates. If you like you can update a copy of  MythTV/packaging/android/Readme.md and post it here. I can then update github with the changes.
You can check your changes by installing okular and opening the Readme.md file with okular.
There is documentation on the format of the file (markdown format) in github and other places on the internet.

**Comment by jfabernathy** [comment]
See if this is an improvement
[Readme.md](https://github.com/MythTV/packaging/files/9331827/Readme.md)

**Comment by jfabernathy** [comment]
I have a few typos. I'll update the readme.md file again

**Comment by jfabernathy** [comment]
updated Readme.md file attached
[Readme.md](https://github.com/MythTV/packaging/files/9333438/Readme.md)

**Comment by jfabernathy** [comment]
Update file attached
[Readme.md](https://github.com/MythTV/packaging/files/9333447/Readme.md)

**Comment by jfabernathy** [comment]
fixed some typos
[Readme.md](https://github.com/MythTV/packaging/files/9333455/Readme.md)

**Comment by bennettpeter** [comment]
CLARIFICATION:
Build keys this way 
keytool -genkey -v -keystore android-release-key.jks -alias mythfrontend -keyalg RSA -keysize 2048 -validity 10000
keytool comes with java
You can use any alias name it does not have to be mythfrontend.
It prompts for passwords and a bunch of other things.
These are the values for the certificate I use for building mythfrontend and leanfront
CN=mythfrontend, O=MythTV, OU=packaging android, L=Boston, ST=MA, C=US
You need to always use the same keystore when building, otherwise you have to uninstall before installing a new version.

I don't know if we need this info, perhaps in a note at the bottom since people will be normally not using it. If you do not create keys it uses debug keys that come with android studio. I think that is what people normally use.

Please update to remove the CLARIFICATION line or include these instructions at the bottom with a reference to them.

**Comment by bennettpeter** [comment]
Those comments above were from before you made changes an hour ago

**Comment by jfabernathy** [comment]
Okay let me edit some more.  As to keys.  I know I'd like a way to get from the debug stage for me locally so it uploads without the adb errors I get sometimes.

**Comment by jfabernathy** [comment]
Okay, I think I've cleaned this up a little. If you like it, please update on github.
[Readme.md](https://github.com/MythTV/packaging/files/9333807/Readme.md)

**Comment by bennettpeter** [comment]
Closed in commit 0ab0daf
